Update README.md
iobroker-community-adapters/ioBroker.ical pull request #390
Opened 2022-03-23 16:49 UTC by Siggi0904

- Korrektur Rechtschreibung
- Ergänzung Hinweis, dass Termine der Vortage nicht angezeigt werden können, dies aber in Arbeit ist
- Anpassung Links in Owncloud/Nextcloud für Export-Link

2022-03-23 16:51 UTC, Feuer-sturm commented
Hallo @Siggi0904 ,aktualisiert du auch gleich die englische Version mit?

2022-03-23 16:53 UTC, Siggi0904 commented
Ja, ich versuche es. Ist mein erster PR.

2022-03-23 17:16 UTC, Siggi0904 commented
@Feuer-sturm kannst du dir mal die Links anschauen? Ich weiß nicht, wie man im GIT-Markdown die Zeichen < > richtig escaped.
Das gilt für beide Sprachen. Danke.

2022-03-23 18:37 UTC, Feuer-sturm requested changes

2022-03-23 18:37 UTC, Feuer-sturm commented on docs/de/README.md
> +  - Hinweis: Termine der Vortage werden aktuell nicht angezeigt, dies ist aber auf der ToDo-Liste
In der Doku sollten nur Dinge beschrieben sein, welche auch implementiert sind. Auch wenn ein Featurewunsch existiert kann man daraus nicht ableiten, wann und ob er implementiert wird.

2022-03-23 18:37 UTC, Feuer-sturm commented on docs/de/README.md
> +Zum Einbinden von gesharten Kalendern einer OwnCloud muss man dort in der Kalenderansicht in OwnCloud diesen Kalender als gesharten Kalender freigeben und dort den Link zum Kalender anzeigen lassen u
Markdown Korrektur für die URL
`https://&lt;DOMAIN&gt;/remote.php/dav/calendars/USER/xxxxxxx_shared_by_xxxxxx?export` ergibt dann: https://&lt;DOMAIN&gt;/remote.php/dav/calendars/USER/xxxxxxx_shared_by_xxxxxx?export

2022-03-23 18:37 UTC, Feuer-sturm commented on docs/de/README.md
> +Bsp.: https://<DOMAIN>/remote.php/dav/calendars/MEINCALENDER/personal/?export  (wichtig ist, dass hier "?export" im Link enthalten ist).
Markdown Korrektur für die URL
`https://&lt;DOMAIN&gt;/remote.php/dav/calendars/MEINCALENDER/personal/?export`

2022-03-23 18:40 UTC, Feuer-sturm commented
@Siggi0904 Danke für deine Änderungen. Hab dir mal ein paar Reviewkommentare hinterlassen. Du kannst dies dann auch gleich in der englischen Version mit korrigieren.

2022-03-26 18:14 UTC, Feuer-sturm commented
@Apollon77 Bitte einmal mergen

2022-03-26 20:15 UTC, merged