Outlook- und office365-Kalender: Bad request - HTTP-Status 400 #423
iobroker-community-adapters/ioBroker.ical pull request #424
Opened 2022-06-12 11:08 UTC by ammawel

Lösung des o.g. issues nach einer Idee von @langeneggerma: Es wird ein header mit user-agent ergänzt.
Längerfristig wäre es vlt. sinnvoll, den user-agent variabel als Parameter der Instanz / des Adapters zu übergeben.

Thread im Forum: https://forum.iobroker.net/topic/55519/ical-outlook-live-com-bad-request

2022-06-12 11:15 UTC, Apollon77 commented
Is "any" user agend header ok or do it need to be an "browser simulated one"?

2022-06-12 14:22 UTC, langeneggerma commented
@Apollon77 sorry, i didn't test that.  I suspect that this is not enough.

@ammawel dann würde ich nicht nur den User Agent sondern die ganzen Header Parameter optional überschreibbar machen. Ich rechne noch mit weiteren unnötigen headern

2022-06-12 14:48 UTC, jens-maus commented
Did someone actually check why such a faked user-agent is required at all? I rather feel that this should be reported to Microsoft rather than immediately adding a faked user-agent header field which just is a workaround of course.

And if such workaround is actually added I would propose to make it dependent on the actual connection Hostname or domain and not changw it for all connections!

2022-06-13 15:43 UTC, langeneggerma commented
Good argument.  It is quite possible that it is a bug at Microsoft.  I wouldn't have found anything at Microsoft.  Actually it makes no sense why a fake user agent is necessary. But as a workaround this works for me.

2022-06-15 20:24 UTC, ammawel commented
An die Entwickler:
Überlegungen über Gründe für einen Header, mögliche Fehler bei Microsoft, eine geplante Kommunikation mit Microsoft etc. sind sicher alle richtig und wichtig.
Aber ist es nicht genauso wichtig, dass bei den "normalen" Anwendern von iobroker der Adapter möglichst schnell wieder das tut was er soll - und wenn es mit einem Workaround ist, dessen Notwendigkeit man nicht unbedingt einsieht, der aber ganz offensichtlich ohne Beeinträchtigung funktioniert?
Danke für ein schnelles Interims-Update,
Achim

2022-06-15 20:42 UTC, jens-maus commented
> und wenn es mit einem Workaround ist, dessen Notwendigkeit man nicht unbedingt einsieht, der aber ganz offensichtlich ohne Beeinträchtigung funktioniert?

Das gilt es ja erst einmal zu beweisen. Ich streube mich weiter dagegen einfach so den `user-agent` header für sämtliche connections des ioBroker.ical adapters zu faken. Wenn überhaupt dann nur für gewisse domänen (eben z.B. nur für die Microsoft/Outlook domäne) und nicht für jegliche Verbindungen. Insofern müsste dieser PR eben noch entsprechend angepasst werden.

2022-06-15 20:43 UTC, jens-maus requested changes

2022-06-15 20:43 UTC, jens-maus commented on main.js
> +		'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'
Please limit the use of a faked `user-agent:` header to the outlook/office365 domain and do not fake it for all connections.

2022-06-16 13:29 UTC, Apollon77 commented
This is a meehhhh topic ;-)

I agree that sending user-agent for all all domains should produce issues with others (especially faking " a special browser version" which might work now but create issues later when the browser gets older).

On the other hand send íng "a user agent header" should not be an issue.

Thats why I asked if e.g. "ioBroker/iCal (<version>)" as generic header would work ok but then  this special "tool" should be ignored by all that check browser versions because unknown - but also would allow service providers to filter our traffic which would also be bad.

The more I think about the more i come to a "optional config field for the instance" to allow entering a user-agent and if entered then it is added ... default: empty

2022-06-16 13:31 UTC, Apollon77 commented
@ammawel 
> - und wenn es mit einem Workaround ist, dessen Notwendigkeit man nicht unbedingt einsieht, der aber ganz offensichtlich ohne Beeinträchtigung funktioniert?

Deine Formulierung ist nicht ganz korrekt ... Sie ist korrekt wenn Du sie ausschliesslich auf Outlook/Outlook365 beziehst ... das sind schätzungsweise <1% der User dieses Adapters

Wir als die Devs müssen schauen das "fixes" für <1% der User nicht die anderen >99% kaputt machen. Und das ist so win Thema was, wie ebend geschrieben, seeehr "meehhh" ist

2022-06-16 14:49 UTC, jens-maus commented
> The more I think about the more i come to a "optional config field for the instance" to allow entering a user-agent and if entered then it is added ... default: empty

Personally, I think that adding yet another GUI option for entering an own user-agent is overkill and just bloats the user interface/experience. Adding more and more optional configuration options is not really a good approach in UI design. Thus, I would still suggest to add a faked `user-agent:` just hard-coded for the outlook/microsoft domains and add comments to the code that this is a workaround because this workaround could easily not be necessary anymore in a few months or years and then we have this unnecessary user-agent UI configuration option which could be the reason for other user issues (e.g. in case a user entered a wrong user-agent string). So don't make it overcomplicated and just add a

```
# necessary because outlook/office suxxs
if(microsoft) { user.agent="XXXX" }
```

and that's it. :)

2022-06-16 18:32 UTC, ammawel commented
@Apollon77 
> Is "any" user agend header ok or do it need to be an "browser simulated one"?

Gerade mit den unten stehenden Einträgen getestet: Zur Zeit scheint jeder beliebige Eintrag zu funktionieren. 

```
'user-agent': 'ioBroker'
'user-agent': 'my Agent'
'user-agent': 'dummy'
```

2022-06-16 19:48 UTC, jens-maus commented
Welcher user agent wird denn standardmäßig geschickt? Gar keiner? Wenn ja, würde IMHO doch nichts dagegensprechen einen generellen user-agent zu setzen (z.b. auf "ioBroker.ical")

2022-06-16 20:16 UTC, AmmaWe commented
Ja, genau das ist es doch: Es wird in der aktuellen Version gar kein Header geschickt, also auch kein User-Agent.

2022-06-16 20:20 UTC, ammawel commented
Ja, genau das ist es doch: Es wird in der aktuellen Version gar kein Header geschickt, also auch kein User-Agent.

2022-06-16 20:56 UTC, jens-maus commented
Hmm. komisch. Ich dachte axios (die http engine die ioBroker.ical nutzt) sendet einen standard `user-agent: axios/0.x.y` mit. Kannst du das bitte nochmal verifizieren das dieser wirklich nicht mitgesendet wird?

2022-06-16 21:37 UTC, ammawel commented
> axios (die http engine die ioBroker.ical nutzt)

... bist du da sicher? Im  Moment bezweifele ich das noch

2022-06-17 09:42 UTC, Apollon77 commented
Yes seems a default is set when header is not specified 
https://github.com/axios/axios/blob/main/lib/adapters/http.js#L170-L181

2022-06-17 09:42 UTC, Apollon77 commented
SO a try would be to set that explicitely ... if request fails then MS did block "axios" calls

2022-06-17 10:01 UTC, jens-maus commented
> Yes seems a default is set when header is not specified https://github.com/axios/axios/blob/main/lib/adapters/http.js#L170-L181

I just checked the code of ioBroker.ical again and was suprised to find out that `request` is still used instead of `axios`. See: https://github.com/iobroker-community-adapters/ioBroker.ical/blob/f40a2b97266133da46006efc3187a9ea0502432a/main.js#L191

Perhaps this explains it a bit more. So we would perhaps be better suited to switch from request to axios first and then see if the default axios user-agent is already enough to please microsoft.

2022-06-17 10:43 UTC, Apollon77 commented
Also an option

2022-06-25 08:31 UTC, klein0r commented
I've replaced ``request`` with ``axios``. Please test with current GitHub version

2022-06-27 10:36 UTC, ammawel commented
> I've replaced `request` with `axios`. Please test with current GitHub version

Sieht bis jetzt gut aus: Sowohl Office365- als auch outlook.com-Kalender werden problemlos aktualisiert.
Vielen Dank!

2022-06-27 13:30 UTC, closed without merging